version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
  app:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  postgresql:
    driver: local
